### ISSUE TITLE
can not find krb5

### ISSUE THREAD

**Issue by chankamlam** [septianw/node-hdfs#3]
```
ken@Ken-MacBookPro hadoopClient % node index.js   
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'krb5'
Require stack:
- /Users/ken/Desktop/jsDemo/hadoopClient/node_modules/hdfs247/index.js
- /Users/ken/Desktop/jsDemo/hadoopClient/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ken/Desktop/jsDemo/hadoopClient/node_modules/hdfs247/index.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ken/Desktop/jsDemo/hadoopClient/node_modules/hdfs247/index.js',
    '/Users/ken/Desktop/jsDemo/hadoopClient/index.js'
  ]
}
```

when I npm install krb5 that yield another issues as below output 

```
> krb5@0.5.4 install /Users/ken/Desktop/jsDemo/hadoopClient/node_modules/krb5
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/krb5/src/module.o
  CXX(target) Release/obj.target/krb5/src/krb5_bind.o
../src/krb5_bind.cc:108:13: warning: 'krb5_cc_close' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_cc_close(krb_context, krb_ccache);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1283:57: note: 'krb5_cc_close' has been explicitly marked
      deprecated here
krb5_cc_close (krb5_context context, krb5_ccache cache) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.fr...
                                                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:158:13: warning: 'krb5_cc_default' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_cc_default(context, &ccache);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1719:18: note: 'krb5_cc_default' has been explicitly marked
      deprecated here
                krb5_ccache *) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10....
                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:209:13: warning: 'krb5_cc_destroy' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_cc_destroy(krb_context, krb_ccache);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1280:59: note: 'krb5_cc_destroy' has been explicitly marked
      deprecated here
krb5_cc_destroy (krb5_context context, krb5_ccache cache) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS....
                                                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:256:25: warning: 'krb5_cc_get_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  const char* cc_name = krb5_cc_get_name(krb_context, krb_ccache);
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1270:60: note: 'krb5_cc_get_name' has been explicitly marked
      deprecated here
krb5_cc_get_name (krb5_context context, krb5_ccache cache) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS...
                                                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:274:25: warning: 'krb5_cc_initialize' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  krb5_error_code err = krb5_cc_initialize(krb_context, krb_ccache, krb_princ);
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1277:32: note: 'krb5_cc_initialize' has been explicitly marked
      deprecated here
                   krb5_principal principal) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", m...
                                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:299:13: warning: 'krb5_cc_initialize' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_cc_initialize(krb_context, krb_ccache, krb_princ);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1277:32: note: 'krb5_cc_initialize' has been explicitly marked
      deprecated here
                   krb5_principal principal) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", m...
                                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:359:13: warning: 'krb5_cc_resolve' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_cc_resolve(krb_context, cc_name.c_str(), &ccache);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1712:19: note: 'krb5_cc_resolve' has been explicitly marked
      deprecated here
                krb5_ccache * ) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10...
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:424:13: warning: 'krb5_cc_store_cred' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_cc_store_cred(krb_context, krb_ccache, &krb_creds);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1287:26: note: 'krb5_cc_store_cred' has been explicitly marked
      deprecated here
                    krb5_creds *creds) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(1...
                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:477:7: warning: 'krb5_free_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      krb5_free_context(context);
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1438:17: note: 'krb5_free_context' has been explicitly marked
      deprecated here
        (krb5_context) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10.8)) __AP...
                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:509:3: warning: 'krb5_free_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  krb5_free_context(krb_context);
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1438:17: note: 'krb5_free_context' has been explicitly marked
      deprecated here
        (krb5_context) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10.8)) __AP...
                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:525:3: warning: 'krb5_free_principal' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  krb5_free_principal(krb_context, krb_princ);
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1742:34: note: 'krb5_free_principal' has been explicitly marked
      deprecated here
        (krb5_context, krb5_principal ) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(...
                                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:540:3: warning: 'krb5_free_creds' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  krb5_free_creds(krb_context, &krb_creds);
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1754:31: note: 'krb5_free_creds' has been explicitly marked
      deprecated here
        (krb5_context, krb5_creds *) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10....
                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:560:13: warning: 'krb5_get_default_realm' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_get_default_realm(context, &realm);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1790:14: note: 'krb5_get_default_realm' has been explicitly
      marked deprecated here
                 char ** ) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10.8)) ...
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:607:25: warning: 'krb5_get_error_message' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  const char* err_msg = krb5_get_error_message(krb_context, err_code);
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:2424:56: note: 'krb5_get_error_message' has been explicitly
      marked deprecated here
krb5_get_error_message (krb5_context, krb5_error_code) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.fra...
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:609:3: warning: 'krb5_free_error_message' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  krb5_free_error_message(krb_context, err_msg);
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:2426:54: note: 'krb5_free_error_message' has been explicitly
      marked deprecated here
krb5_free_error_message (krb5_context, const char *) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.frame...
                                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:635:13: error: no matching function for call to 'krb5_get_init_creds_password'
      err = krb5_get_init_creds_password(krb_context, 
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:2302:1: note: candidate function not viable: 4th argument
      ('const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *'))
      would lose const qualifier
krb5_get_init_creds_password
^
../src/krb5_bind.cc:699:13: warning: 'krb5_init_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_init_context(&context);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1434:19: note: 'krb5_init_context' has been explicitly marked
      deprecated here
        (krb5_context *) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10.8)) __...
                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:750:13: warning: 'krb5_kt_resolve' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      err = krb5_kt_resolve(krb_context, kt_name.c_str(), &ktid);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:1682:19: note: 'krb5_kt_resolve' has been explicitly marked
      deprecated here
                krb5_keytab * ) KERBEROS_APPLE_DEPRECATED("use GSS.framework") __API_DEPRECATED("Use GSS.framework", macos(10.0, 10...
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:73:53: note: expanded from macro 'KERBEROS_APPLE_DEPRECATED'
#define KERBEROS_APPLE_DEPRECATED(x) __attribute__((deprecated(x)))
                                                    ^
../src/krb5_bind.cc:815:13: error: no matching function for call to 'krb5_get_init_creds_keytab'
      err = krb5_get_init_creds_keytab(krb_context,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/krb5/krb5.h:2314:1: note: candidate function not viable: 6th argument
      ('const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *'))
      would lose const qualifier
krb5_get_init_creds_keytab
^
17 warnings and 2 errors generated.
make: *** [Release/obj.target/krb5/src/krb5_bind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@12/12.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node@12/12.18.2/bin/node" "/usr/local/Cellar/node@12/12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ken/Desktop/jsDemo/hadoopClient/node_modules/krb5
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN hadoopclient@1.0.0 No description
npm WARN hadoopclient@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! krb5@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the krb5@0.5.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ken/.npm/_logs/2020-10-21T06_18_19_043Z-debug.log
```

**Comment by Raboo** [comment]
Got the same problem, did you find a work-around?

**Comment by Raboo** [comment]
My workaround was to add krb5 as dependency. But to build krb5 you need a bunch of stuff like `krb5-dev python3 make gcc g++`.
When running a built krb5 you only need `krb5-libs`.
(this is alpine package names, names will differ in other distros and platforms)

**Comment by septianw** [comment]
thank you @Raboo i didn't think of kerberos while i make this.
